In [9]:
#Genai class4 Pandas

import pandas as pd

df = pd.DataFrame({

    'Name': ['A','B','C','D','E','F','G','H'],

    'Age': [23,45,31,35,62,18,29,40],

    'Gender': ['M','F','M','F','F','M','M','F'],

    'Salary': [50000,60000,55000,65000,70000,40000,52000,58000],

    'Department': ['HR','IT','IT','HR','Finance','IT','HR','Finance']

})
print("First 5 rows:")
print(df.head())
print("\nLast 5 rows:")
print(df.tail())

First 5 rows:
  Name  Age Gender  Salary Department
0    A   23      M   50000         HR
1    B   45      F   60000         IT
2    C   31      M   55000         IT
3    D   35      F   65000         HR
4    E   62      F   70000    Finance

Last 5 rows:
  Name  Age Gender  Salary Department
3    D   35      F   65000         HR
4    E   62      F   70000    Finance
5    F   18      M   40000         IT
6    G   29      M   52000         HR
7    H   40      F   58000    Finance

In [11]:
df.shape

(8, 5)

In [12]:
df.columns

Index(['Name', 'Age', 'Gender', 'Salary', 'Department'], dtype='object')

In [14]:
#position number of columns and rows 
df.index

RangeIndex(start=0, stop=8, step=1)

In [15]:
df.info() #where we extract the information about the data types of the columns.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      object
 1   Age         8 non-null      int64
 2   Gender      8 non-null      object
 3   Salary      8 non-null      int64
 4   Department  8 non-null      object
dtypes: int64(2), object(3)
memory usage: 448.0+ bytes

In [18]:
df.describe() #where we extract the statistical summary of the numerical columns.

             Age        Salary
count   8.000000      8.000000
mean   35.375000  56250.000000
std    13.824797   9300.537619
min    18.000000  40000.000000
25%    27.500000  51500.000000
50%    33.000000  56500.000000
75%    41.250000  61250.000000
max    62.000000  70000.000000

In [19]:
df.memory_usage() #where we extract the memory usage of the dataframe.

Index         128
Name           64
Age            64
Gender         64
Salary         64
Department     64
dtype: int64

In [17]:
df.dtypes

Name          object
Age            int64
Gender        object
Salary         int64
Department    object
dtype: object

In [21]:
df[['Name','Salary']]

  Name  Salary
0    A   50000
1    B   60000
2    C   55000
3    D   65000
4    E   70000
5    F   40000
6    G   52000
7    H   58000

In [22]:
df.loc[0:3, ['Name','Salary']]

  Name  Salary
0    A   50000
1    B   60000
2    C   55000
3    D   65000

In [25]:
df.at[1,'Name'] #to extract the value of a cell using the label-based indexing.

'B'

In [28]:
df[df['Age'] < 30] #to filter the rows based on a condition.

  Name  Age Gender  Salary Department
0    A   23      M   50000         HR
5    F   18      M   40000         IT
6    G   29      M   52000         HR

In [32]:
df[(df['Age'] > 30) & (df['Salary'] > 50000)] #to filter the rows based on multiple conditions.

  Name  Age Gender  Salary Department
1    B   45      F   60000         IT
2    C   31      M   55000         IT
3    D   35      F   65000         HR
4    E   62      F   70000    Finance
7    H   40      F   58000    Finance

In [37]:
df[df['Name'].str.contains('B')] #to filter the rows where the age is greater than 30.

  Name  Age Gender  Salary Department
1    B   45      F   60000         IT

In [44]:
df.query('Age > 30 & Salary > 50000') #to filter the rows based on multiple conditions using the query method.

  Name  Age Gender  Salary Department
1    B   45      F   60000         IT
2    C   31      M   55000         IT
3    D   35      F   65000         HR
4    E   62      F   70000    Finance
7    H   40      F   58000    Finance

In [46]:
df.query('Age > 30 and Gender == "M"') #to filter the rows based on multiple conditions using query method.

  Name  Age Gender  Salary Department
2    C   31      M   55000         IT

In [47]:
df.sort_values(by='Age') #to sort the dataframe based on a column.

  Name  Age Gender  Salary Department
5    F   18      M   40000         IT
0    A   23      M   50000         HR
6    G   29      M   52000         HR
2    C   31      M   55000         IT
3    D   35      F   65000         HR
7    H   40      F   58000    Finance
1    B   45      F   60000         IT
4    E   62      F   70000    Finance

In [50]:
df.sort_values(by='Age', ascending=False) #to sort the dataframe based on a column.

  Name  Age Gender  Salary Department
4    E   62      F   70000    Finance
1    B   45      F   60000         IT
7    H   40      F   58000    Finance
3    D   35      F   65000         HR
2    C   31      M   55000         IT
6    G   29      M   52000         HR
0    A   23      M   50000         HR
5    F   18      M   40000         IT

In [52]:
df.sort_index(ascending=False) #to sort the dataframe based on the index.

  Name  Age Gender  Salary Department
7    H   40      F   58000    Finance
6    G   29      M   52000         HR
5    F   18      M   40000         IT
4    E   62      F   70000    Finance
3    D   35      F   65000         HR
2    C   31      M   55000         IT
1    B   45      F   60000         IT
0    A   23      M   50000         HR

In [53]:
df['Bonus'] = df['Salary'] * 0.1 #to create a new column based on the existing columns.
df.head()

  Name  Age Gender  Salary Department   Bonus
0    A   23      M   50000         HR  5000.0
1    B   45      F   60000         IT  6000.0
2    C   31      M   55000         IT  5500.0
3    D   35      F   65000         HR  6500.0
4    E   62      F   70000    Finance  7000.0

In [ ]:
# Correct way to assign Bonus based on Department column
df['Bonus'] = df.apply(lambda row: row['Salary'] * 0.2 if row['Department'] == 'HR' else row['Salary'] * 0.1, axis=1)
df.head()

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().